✨ 使用最新的方法获取版本更新

diff --git a/.github/workflows/build_push.yml b/.github/workflows/build_push.yml
--- a/.github/workflows/build_push.yml
+++ b/.github/workflows/build_push.yml
@@ -38,7 +38,13 @@ jobs:
         id: extract_version
         run: |
           latest_url=${{ steps.get_url.outputs.latest_url }}
-          version=$(basename "$latest_url" | sed -n 's/.*-\([0-9.]*\).zip/\1/p')
+          echo "Latest URL: $latest_url"
+          version=$(basename "$latest_url" | sed -n 's/.*easybot-[^-]*-x64-\([0-9]\+\.[0-9]\+\.[0-9]\+-[0-9a-z]\+\)\..*/\1/p')
+          if [ -z "$version" ]; then
+            echo "Error: Failed to extract version from URL."
+            exit 1
+          fi
+          echo "Extracted version: $version"
           echo "::set-output name=version::$version"
 
       - name: Compare hash with version file
